### ISSUE TITLE
Floorplan annotations

### ISSUE THREAD

**Issue by ywyue** [facebookresearch/habitat-matterport3d-dataset#6]
Thanks for your amazing work! I wonder is there 2D floorplan annotation for the scene (Or do you have any plans to release this kind of annotation in the near future)?

Best,
Yuanwen

**Comment by srama2512** [comment]
Hi @ywyue ,

We do not have any floorplan annotations at the moment. There are no immediate plans to get these.

**Comment by ywyue** [comment]
Thanks!
