### ISSUE TITLE
Using the dataset in NVIDIA isaac 

### ISSUE THREAD

**Issue by sai-prasanna** [facebookresearch/habitat-matterport3d-dataset#8]
Hi, thanks for providing this dataset for research. I was wondering if anyone managed to import this dataset into NVIDIA isaac sim. The glb files are directly importable into isaac, but I am not really sure if it's amenable to spawn robots into it/generate navigation meshes, get semantic camera outputs etc. Any pointers would be really helpful!

**Comment by dhruvbatra** [comment]
Out of scope for us. Closest I've seen in Section 5 in this paper: https://navigation-locomotion.github.io/

Also, you don't have to that. You can simply navigation policies in Habitat and combine with locomotion policies in Isaac as done in this paper: https://www.joannetruong.com/projects/vinl.html
